### PR TITLE
refactor: Make MetaDB Datastore only

### PR DESCRIPTION
**Pull request by yuryu**
**What type of PR is this?**
/kind refactor

**What this PR does / Why we need it**:
Remove the intermediate MetaDB interface and move methods in
the datastore.Driver struct to the new MetaDB struct.
We will focus on the GCP implementation and remove the redundant code.

This is per #174.

**Which issue(s) this PR fixes**:

Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by loranger2k — COMMENTED** [review]
Would it make sense to actually define an interface for the MetaDB to make it easier for other Cloud Provider to understand what needs to be implemented?

**Comment by yuryu** [comment]
That was the original intention, but it actually didn't work well as intended. We want to focus on the GCP implementation for now and expedite the development process. We could add an abstraction layer later when we need to.

**Comment by loranger2k** [comment]
But we could still have an interface defined at the MetaDB level, no?

**Comment by yuryu** [comment]
We could, but that doesn't guarantee the interface can be implemented with another provider. Also I think this was the wrong abstraction. We should implement more primitive operations as a driver and move most of the logic out of it, but we ended up with putting everything in the driver. If we want to implement an additional backend provider, I would suggest change the implementation model. I'd like to remove the development overhead until we have a better model.

**Comment by loranger2k** [comment]
Sure. I suggested to leave the interface since nothing changed in any of the functions after the refactor.

**Review by loranger2k — APPROVED** [review]
+1

**Pull request merged**
