### PR TITLE
fix: hitting eof when read is not completed

### PR DESCRIPTION
**Pull request by vasconcelosvcd**
**What type of PR is this?**
/kind fix

**Special notes for your reviewer**:

In some cases when hitting `EOF` the buffer still has some bytes to be read.
With this change we ensure that the bytes left are read before hitting `EOF`

### CODE REVIEW

**Review by loranger2k — APPROVED** [review]
👍  This fixes an issue we have seen of missing bytes when reading a gRPC stream where the last message read from the buffer contains bytes and err == EOF to signal the end of the buffer.

**Review by loranger2k — CHANGES_REQUESTED** [review]
I am seeing other instances in this file where gRPC streams are read and the last bytes not processed before testing for EOF.
line 229
line 306
line 358
line 515

**Comment by yuryu** [comment]
Can we get a test case for this?

**Review by yuryu — CHANGES_REQUESTED** [review]
marking as request change

**Comment by yuryu** [comment]
I looked around and it looks like Recv() returns nil if err != nil. Am I missing something?
https://github.com/googleforgames/open-saves/blob/main/api/open_saves_grpc.pb.go#L311

**Comment by loranger2k** [comment]
According to the documentation of the `Reader` interface of io.go, the `Read(p []byte) (n int, err error)` function can return both values that were read from a buffer + EOF as the error.
Although this is not usually the case, this happened in our client implementation when using the multipart.NewReader object. All other readers are either returning an error or data, but not both.
Closing this issue as this is not an error in Open Saves.

**Comment by yuryu** [comment]
It's already closed but the streaming clients don't implement `io.Reader` (it's handled internally within grpc) or behave like `Reader.Read`. They just use the same error code `io.EOF`. I agree it's confusing but I agree this is WAI.

**Pull request closed without merging**
