### PR TITLE
fix: support for record with only NumberOfChunks in Datastore (#391)

### LINKED ISSUE #391: Backward compatibility issue with Record created with NumberOfChunks
**What happened**:
We have data that has been created with the older open saves API, which saved NumberOfChunks as a column in the record objects. The changes introduced to replace NumberOfChunks but ChunkCount didn't take into effect that the deserialization of the datastore object would fail because of the field removed from the struct (effectively a change in schema).

**What you expected to happen**:
I expect Open Saves to be able to load records even if they have a field called NumberOfChunks, at a minimum. Better would have to have the number of chunks copied in the friend ChunkCount.

**How to reproduce it (as minimally and precisely as possible)**:
Using an older version of Open Saves, create chunk records and upload a blob, then set the NumberOfChunks to 1. Upgrade to the latest version and try to get the record by ID or call query record.

**Anything else we need to know?**:

**Environment**:
- Open Saves version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

### PR DESCRIPTION
**Pull request by loranger2k**
**What type of PR is this?**
/kind fix

**What this PR does / Why we need it**:
Ensure Open Saves is able to read both NumberOfChunks or ChunkCount from Datastore until we have migrated all of the older data and can get rid of this backward compatibility work around.

Closes #391

**Special notes for your reviewer**:
These changes have been tested with legacy and new records from our development environment.

### CODE REVIEW

**Comment by loranger2k** [comment]
Not sure why the build failed. Re-running:

/gcbrun

**Comment by yuryu** [comment]
#393 is already in the works but is this a different approach or to fix another issue?
Please don't add another field to the structs, just handle the variance in `Load` so we won't need to worry about it in other parts of the code.

**Comment by loranger2k** [comment]
#393 is a slightly different approach as it is not reading NumberOfChunks, only ChunkCount.

How do you propose to handle the variance? By creating a local struct with the additional field and copy back to the Record struct once done?

**Comment by yuryu** [comment]
Something like this should work? I added test cases.

https://github.com/googleforgames/open-saves/compare/main...yuryu:open-saves:number-count

**Comment by loranger2k** [comment]
It is working code, but it is not loading the legacy values in Datastore, i.e. NumberOfChunks. This won't work for us since we need to load NumberOfChunks when in Datastore. Otherwise all existing record with NumberOfChunks will show up with ChunkCount=0.

**Comment by yuryu** [comment]
It should load the legacy value (that's what `Load()` does). Do you mean you have some other tools that directly access Datastore?

**Comment by loranger2k** [comment]
I totally misunderstood how the datastore LoadStruct works. I thought the LoadStruct was actually loading the value from Datastore. But it looks like the values are already there when this is called, and that datastore.LoadStruct simply copy the values to the struct.

**Comment by loranger2k** [comment]
Close this PR in favor of original fix proposed in #393

**Pull request closed without merging**
